services:
  gitlab:
    container_name: "${GITLAB_CONTAINER_NAME}"
    image: "gitlab/gitlab-ce:latest"
    hostname: "${GITLAB_HOST}"
    environment:
      GITLAB_ROOT_EMAIL: "${GITLAB_ROOT_EMAIL}"
      GITLAB_ROOT_PASSWORD: "${GITLAB_ROOT_PASSWORD}"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_HOST}'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false 

        # SMTP
        gitlab_rails['smtp_enable'] = ${SMTP_ENABLE}
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${SMTP_USER}"
        gitlab_rails['smtp_password'] = "${SMTP_PASS}"
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_email_from'] = "${SMTP_FROM}"
        gitlab_rails['gitlab_email_reply_to'] = "${SMTP_REPLY_TO}"

        # Performances (facultatif si petit serveur)
        puma['worker_processes'] = 1
        sidekiq['max_concurrency'] = 5
        prometheus_monitoring['enable'] = true

        # Réduction des logs GitLab
        gitlab_rails['log_level'] = :warn
        sidekiq['log_level'] = :warn
        gitlab_workhorse['log_format'] = "none"

        # Rotation interne des logs GitLab
        logrotate['enable'] = true
        logrotate['rotate'] = 7
        logrotate['size'] = '100M'
    ports:
      - "${HTTP_PORT}:80"
      - "${SSH_PORT}:22"
    volumes:
      - "./config:/etc/gitlab"
      - "./logs:/var/log/gitlab"
      - "./data:/var/opt/gitlab"
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "3"
